---
title: "Preparação variáveis nos cenários futuros"
author: "Reginaldo Ré"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
knit: (function(...) {source("../config/script_funcoes_auxiliares.R"); myKnit(...)})
output:
  html_document:
    df_print: paged
    number_sections: TRUE    # seções numeradas automaticamente
    toc: true                # construir o sumário
    toc_float: true          # colocar o sumário flutuante no canto superior   esquerdo
    toc_depth: 3             # o sumário conterá três níveis de profundidade: capitulo, seção e subseção
    theme: cerulean          # tema de cores estilo de fonte, use o "united" para um tema monocromico
    code_folding: hide       # inclu  i botão para mostrar/esconder código fonte
editor_options: 
  chunk_output_type: inline
---
<style>
div.main-container {
    width: 100%;
    max-width: unset;
}
</style>

```{r message=FALSE, warning=FALSE, include=FALSE}
source("../config/script_funcoes_auxiliares.R") 
```

# Configurações Iniciais 
## Arquivos e pastas de entrada e saída

```{r arquivos_pastas_entrada, eval=T, include=T}
nome_shape_grid_estudo <- here("geoprocessamento/output_data/grid/upper_prpy_grid_10k_6933.shp")
nome_shape_SRTM <- here("geoprocessamento/output_data/shape_srtm_escalonado/srtm_10k_6933.shp")
pastas_shape_futuro <- here("geoprocessamento/output_data/shape_bio_futuro_escalonadas")
```

```{r arquivos_pastas_saida, eval=T, include=T}
pasta_shape_futuro_pca <- here("preparacao_variaveis_futuro/output_data/shape_pca_futuro")
pasta_shape_futuro_preditoras <- here("preparacao_variaveis_futuro/output_data/shape_preditoras_futuro")

if (!dir_exists("output_data")){
  dir_create("output_data")
}
```

## Variaveis de Controle

```{r variaveis_controle, eval=T, include=T}
nomes_especies <- c("sp1","sp2","sp3","sp4","sp5","sp6","sp7","sp8","sp9","sp10","sp11","sp12","sp13","sp14","sp15","sp16","sp17","sp18","sp19","sp20","sp21","sp22","sp23","sp24","sp25","sp26","sp27","sp28","sp29","sp30","sp31","sp32","sp33","sp34","sp35","sp36","sp37","sp38","sp39","sp40","sp41","sp42","sp43","sp44","sp45","sp46","sp47","sp48","sp49","sp50","sp51","sp52","sp53")

variaveis_remover <- c("endorhe", "main_ri")

vari_normalizacao <- c("srtm", "bio_01", "bio_02", "bio_03", "bio_04", 	"bio_05", "bio_06", "bio_07", "bio_08", "bio_09", "bio_10", "bio_11", "bio_12", "bio_13", "bio_14", "bio_15", 	"bio_16", "bio_17", "bio_18", "bio_19") 

nr_comp_pca <- 13

nome_var_preditoras <-c("dim_1_todas","dim_2_todas")
```

# Preparação das variáveis

## Carregamento e Junção das variáveis 

```{r juncao_preditoras_pa, eval=T, include=T}
shape_grid_estudo <- nome_shape_grid_estudo %>%
  readOGR(verbose = F)

shape_grid_SRTM <- nome_shape_SRTM %>%
  readOGR(verbose = F)
```

# Cálculo das PCA dos cenários futuros
```{r calcular_pca_futuro, eval=T, include=T}
if (!dir_exists(pasta_shape_futuro_pca)){
  dir_create(pasta_shape_futuro_pca)
}

pastas_cenarios <- pastas_shape_futuro %>%
  dir_ls()

for (cenario in pastas_cenarios){
  output_folder_pca <- pasta_shape_futuro_pca %>% 
    path(cenario %>% path_split() %>% pluck(1,last))
  output_folder_preditoras <- pasta_shape_futuro_preditoras %>% 
    path(cenario %>% path_split() %>% pluck(1,last))
  
  if (!dir_exists(output_folder_pca) || !dir_exists(output_folder_preditoras)){
    if (dir_exists(output_folder_pca))
      dir_delete(output_folder_pca)
    if (dir_exists(output_folder_preditoras))
      dir_delete(output_folder_preditoras)
    dir_create(output_folder_pca)
    dir_create(output_folder_preditoras)
    
    todas_var <- shape_grid_estudo %>%
      get_var_shp() %>%
      add_var_shp(shape_grid_SRTM) %>%
      add_var_shp(
          cenario %>% 
          dir_ls(glob = "*.shp") %>%
          pluck(1)
        ) %>%
      remove_var(variaveis_remover) %>%
      remove_var(nomes_especies) %>%
      center_scale(vari_normalizacao)
    
    pca_futuro <- todas_var %>%
      calc_pca(nr_comp_pca, "Todas")
    
    filename_pca_futuro <- "pca_" %>%
      paste0(
          output_folder_pca %>% 
          path_split() %>% 
          pluck(1, last) 
      ) %>%
      paste0(".shp")
    
    shape_grid_estudo %>%
      SpatialPointsDataFrame(
        shape_grid_estudo@data %>% 
          select(id_celula) %>% 
          bind_cols(pca_futuro$ind$coord %>% as.data.frame()),
        match.ID = F
      ) %>%
      writeOGR(dsn = output_folder_pca %>% path(filename_pca_futuro),
               layer = ".",
               driver = "ESRI Shapefile")
    
    preditoras_futuro <- todas_var %>%
      bind_cols(pca_futuro$ind$coord %>% as.data.frame()) %>%
      select(nome_var_preditoras %>% all_of())
    
    filename_preditoras_futuro <- "preditoras_" %>%
      paste0(
          output_folder_preditoras %>% 
          path_split() %>% 
          pluck(1, last) 
      ) %>%
      paste0(".shp")
    
    shape_grid_estudo %>%
      SpatialPointsDataFrame(
        shape_grid_estudo@data %>% 
          select(id_celula) %>% 
          bind_cols(preditoras_futuro),
        match.ID = F
      ) %>%
      writeOGR(dsn = output_folder_preditoras %>% path(filename_preditoras_futuro),
               layer = ".",
               driver = "ESRI Shapefile")  
  }
}
```