---
title: "Distribuição das Espécies no Futuro"
author: "Reginaldo Ré"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
knit: (function(...) {source("../config/script_funcoes_auxiliares.R"); myKnit(...)})
output:
  html_document:
    df_print: paged
    number_sections: TRUE    # seções numeradas automaticamente
    toc: true                # construir o sumário
    toc_float: true          # colocar o sumário flutuante no canto superior esquerdo
    toc_depth: 3             # o sumário conterá três níveis de profundidade
    theme: cerulean          # tema de cores estilo de fonte,
    code_folding: hide       # inclui botão para mostrar/esconder código fonte
editor_options: 
  chunk_output_type: inline
  
  
---
<style>
div.main-container {
    width: 100%;
    max-width: unset;
}
</style>

```{r message=FALSE, warning=FALSE, include=FALSE}
source("../config/script_funcoes_auxiliares.R") 
```

# Configurações Iniciais 
## Arquivos e pastas de entrada e saída

```{r arquivos_pastas_entrada, eval=T, include=T}
# Nome do arquivo shapefile que contém a grid de estudo.
nome_shape_grid_estudo <- here("geoprocessamento/output_data/grid/upper_prpy_grid_10k_6933.shp")

# Nome do arquivo shapefile com a matriz de presenças/ausências.
nome_shape_matriz_pa <- here("ocorrencias/output_data/upper_prpy_pres_aus_10k_6933.shp")

# Nome da pasta com os modelos treinados, um arquivo para cada espécie.
pasta_modelos_treinados <- here("treinamento_avaliacao/output_data/modelos_treinados/")

# Nome dos arquivos shapefile com as variáveis nos cenários futuros escolhidas como preditoras. 
pastas_var_futuro <- here("preparacao_variaveis_futuro/output_data/shape_preditoras_futuro/")
```


```{r arquivos_pastas_saida, eval=T, include=T}
# Nome da pasta que irá conter as predições nos cenários futuros para cada uma das espécies.
pasta_distribuicao_futuro <- here("distribuicao_futuro/output_data")

if (!dir_exists("output_data")){
  dir_create("output_data")
}
```

## Variaveis de Controle

```{r variaveis_controle, eval=T, include=T}
# Nomes das espécies que serão utilizadas no estudo. Os nomes devem ser idênticos àqueles contidos no arquivo de ocorrências.
# Caso queira utilizara todas as espécies do arquivo: nomes_especies <- NULL.
nomes_especies <- c("sp11","sp12","sp13","sp14","sp15","sp16","sp17","sp18","sp19","sp20","sp21","sp22","sp23","sp24","sp25","sp26","sp27","sp28","sp29","sp30","sp31","sp32","sp33","sp34","sp35","sp36","sp37","sp38","sp39","sp40","sp41","sp42","sp43","sp44","sp45","sp46","sp47","sp48","sp49","sp50","sp51","sp52","sp53")


# Nome da espécie cujos resultados serão mostrados nos gráficos do final desta parte do script.
nome_especie_distr <- "sp53"

# Nomes dos métodos de predição usados no treinamento e teste dos modelos e, também, para a predição da distribuição nos cenários futuros.
alg_predicao <- c("bioclim","DEuc", "Mahal", "maxent", "maxlike", "Enfa", "rf", "svm", "glm")
#alg_predicao <- c("rf")

# Critério para determinação dos limiares (thresholds) para cada método de predição.
# 1:sp=se, 2:max(se+sp), 3:min(cost), 4:minROCdist, 5:max(kappa), 6:max(ppv+npv), 7:ppv=npv, 8:max(NMI), 9:max(ccr), 10: prevalence
criterio_thres <- 2
```

# Avaliação dos modelos de predição

## Preparação das variáveis para os modelos

```{r preparar_df_predicao,  eval=T, include=T}
shape_grid_estudo <- nome_shape_grid_estudo %>% 
  readOGR(verbose = F)

shape_matriz_pa <- nome_shape_matriz_pa %>% 
  readOGR(verbose = F)

df_pres_aus <- shape_matriz_pa@data %>%
  select(
      nomes_especies %>% 
        to_snake_case() %>% 
        abbreviate(minlength = 10) %>%
        unname() %>% 
        all_of()
      ) 
```


## Predição da distribuição da espécie usando os melhores modelos
```{r pred_distribuicao, eval=T, include=T}
pastas_cenarios <- pastas_var_futuro %>%
  dir_ls(type = "directory")

cenarios_list <- list()
for (cenario in pastas_cenarios){
  df_var_preditoras <- cenario %>% 
          dir_ls(glob = "*.shp") %>%
          pluck(1) %>%
          readOGR(verbose = F) %>%
          get_var_shp()
  # df_var_preditoras <- NA %>%
  #     add_var_shp(
  #       cenario %>% 
  #         dir_ls(glob = "*.shp") %>%
  #         pluck(1) %>%
  #         readOGR(verbose = F)
  #     )
  cenarios_list[[cenario %>% path_split() %>% pluck(1, last)]] <- df_var_preditoras
}

for (especie in names(df_pres_aus)){
  df_pres_aus %>% 
    select(especie %>% all_of()) %>%
    predict_to_folder(
      cenarios_list,
      pasta_modelos_treinados, 
      shape_grid_estudo,
      alg_predicao, 
      criterio_thres, 
      pasta_distribuicao_futuro
    )
}
```
  
  
```{r geracao_arquivos_consenso}
summ_sp_predictions_from_folder(pasta_distribuicao_futuro)
```
  
```{r}
summ_scenarios_predictions_from_folder(pasta_distribuicao_futuro)
```

 